local objects = {
    {
      id = 11,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 81.3333,
      y = 654.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 15,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 35.3333,
      y = 620,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 16,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 81.3333,
      y = 588.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 17,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 100,
      y = 587.333,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 18,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 118,
      y = 586.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 19,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 200,
      y = 540,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 20,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 266.667,
      y = 476.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 21,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 198.667,
      y = 396.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 22,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 209.333,
      y = 267.333,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 23,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 256.667,
      y = 334,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 24,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 228.667,
      y = 270.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 25,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 111.333,
      y = 270.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 26,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 82,
      y = 303.333,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 27,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 16,
      y = 337.333,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 28,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 15.3333,
      y = 356.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 29,
      name = "Coin",
      type = "",
      shape = "rectangle",
      x = 16,
      y = 380.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 49,
      visible = true,
      properties = {}
    },
    {
      id = 30,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 17.3333,
      y = 508,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    },
    {
      id = 31,
      name = "Gem",
      type = "",
      shape = "rectangle",
      x = 64.6667,
      y = 302.667,
      width = 16,
      height = 16,
      rotation = 0,
      gid = 54,
      visible = true,
      properties = {}
    }

}

return objects